Feature/issue 4 develop snmp library
sentrysoftware/snmp pull request #5
Opened 2023-12-11 15:16 UTC by kawtarBK9

* Developed SNMP client
* Updated license headers
* Updated the README.md file
* Updated the index.md in site/markdown

2023-12-11 16:16 UTC, CherfaElyes commented on .idea/.gitignore
You should delete all IDEA-related directories and files: ".idea",

2023-12-11 16:24 UTC, kawtarBK9 commented on .idea/.gitignore
It's done !

2023-12-11 18:04 UTC, NassimBtk requested changes
Thank you @kawtarBK9, couple of small changes then we should be good.

2023-12-11 18:13 UTC, NassimBtk requested changes

2023-12-11 18:13 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/snmp/client/SnmpResult.java
> +public class SnmpResult
Please format this class.

2023-12-11 18:13 UTC, NassimBtk commented on src/main/java/org/sentrysoftware/snmp/client/SnmpClient.java
> +	static public final String socketType = "Standard";
The constant should be declared as the following:
```java
	public static final String SOCKET_TYPE = "Standard";
```

2023-12-11 18:24 UTC, NassimBtk commented on .idea/.gitignore
Already done! Thank you @CherfaElyes and @kawtarBK9!

2023-12-11 22:24 UTC, bertysentry commented on src/site/markdown/index.md
> +* Establishing a secure connection to a remote server
These come from the SSH client 😅

2023-12-12 09:41 UTC, NassimBtk requested changes

2023-12-12 09:41 UTC, NassimBtk commented on .idea/.gitignore
Why is `.idea` being re-added once again, please delete it. Update your .gitignore as follows:

```
### IntelliJ IDEA ###
.idea
*.iws
*.iml
*.ipr
```

2023-12-12 10:08 UTC, NassimBtk approved these changes

2023-12-12 10:18 UTC, merged